### ISSUE TITLE
Cannot start up the simulation server

### ISSUE THREAD

**Issue by archman** [dls-controls/coniql#7]
Hello,
After installing `coniql` (19dd93becf0e088192e3ffaa4cb3ca5c73251ed9), and all the dependencies, I've tried to start the simulation server as the documentation said: `python -m coniql`, but have got the following error:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/coniql/__main__.py", line 4, in <module>
    main()
  File "/home/tong/graphql-env/lib/python3.6/site-packages/coniql/app.py", line 80, in main
    web.run_app(app)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/aiohttp/web.py", line 433, in run_app
    reuse_port=reuse_port))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/tong/graphql-env/lib/python3.6/site-packages/aiohttp/web.py", line 305, in _run_app
    await runner.setup()
  File "/home/tong/graphql-env/lib/python3.6/site-packages/aiohttp/web_runner.py", line 232, in setup
    self._server = await self._make_server()
  File "/home/tong/graphql-env/lib/python3.6/site-packages/aiohttp/web_runner.py", line 331, in _make_server
    await self._app.startup()
  File "/home/tong/graphql-env/lib/python3.6/site-packages/aiohttp/web_app.py", line 389, in startup
    await self.on_startup.send(self)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/home/tong/graphql-env/lib/python3.6/site-packages/tartiflette_aiohttp/__init__.py", line 99, in _cook_on_startup
    sdl=sdl, schema_name=schema_name, modules=modules
  File "/home/tong/graphql-env/lib/python3.6/site-packages/tartiflette/engine.py", line 296, in cook
    custom_default_arguments_coercer,
  File "/home/tong/graphql-env/lib/python3.6/site-packages/tartiflette/schema/bakery.py", line 54, in bake
    schema = SchemaBakery._preheat(schema_name)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/tartiflette/schema/bakery.py", line 26, in _preheat
    schema = schema_from_sdl(sdl, schema_name=schema_name)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/tartiflette/schema/transformer.py", line 965, in schema_from_sdl
    document_node = parse_to_document(sdl)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/tartiflette/language/parsers/lark/parser.py", line 41, in parse_to_document
    parsed = _LARK_PARSER.parse(sdl)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/parser_frontends.py", line 125, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 83, in parse
    for token in stream:
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "/home/tong/graphql-env/lib/python3.6/site-packages/lark/lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for '/' at line 1 col 1

/home/tong/graphql-env/lib/python3.6/sit
^

Expecting: {'UNION', 'ENUM', 'STRING', 'INPUT', 'SCALAR', 'EXTEND', 'TYPE', 'DIRECTIVE', 'INTERFACE', 'SCHEMA', 'LONG_STRING'}
```
Could you please help? Thanks.
Tong

**Comment by thomascobb** [comment]
Please can you list the conents of `/home/tong/graphql-env/lib/python3.6/site-packages/coniql`?

**Comment by archman** [comment]
> Please can you list the contents of `/home/tong/graphql-env/lib/python3.6/site-packages/coniql`?
```
app.py            device_config.py  plugin.py     resolvers.py  _version_git.py
caplugin.py       __init__.py       pvaplugin.py  simplugin.py
coniql_schema.py  __main__.py       __pycache__   types.py
```

**Comment by thomascobb** [comment]
Ah, I forgot to add schema.gql to the package. It works from the git clone, but not from the installed package. I'll push a fix for this tomorrow...

**Comment by archman** [comment]
> Ah, I forgot to add schema.gql to the package. It works from the git clone, but not from the installed package. I'll push a fix for this tomorrow...

Yes I installed via `pip install`. Now it works after I copied that file into the library. Thanks.

**Comment by thomascobb** [comment]
I've tidied up the packaging and sorted out the dependencies and package data and the result is on PyPI so now `pip install` should work as expected. Thanks for the bug report!
